### PR TITLE
Parameter endpoint

### PR DESCRIPTION
**Pull request by Debora38**

### CODE REVIEW

**Comment by rockem** [comment]
@Debora38 Is this something you required? why did you close the PR?

**Comment by Debora38** [comment]
> @Debora38 Is this something you required? why did you close the PR?

Hi @rockem I didn't think this was the way to approach it but I wanted to test it out, however GHA wouldn't run without maintain permissions. I'd need to use the api.eu endpoint, would the code here work or would you think of a better approach?

**Comment by rockem** [comment]
@Debora38 I actually think it will work fine and will be flexible if OpsGenie change their URL, another approach is to be more strict and add a EU boolean. wdyt?

**Comment by Debora38** [comment]
> @Debora38 I actually think it will work fine and will be flexible if OpsGenie change their URL, another approach is to be more strict and add a EU boolean. wdyt?

I opened a different draft PR with a boolean, wanna see if it makes sense?

**Pull request closed without merging**
